variables:
  GIT_DEPTH: 1
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/0/$CI_PROJECT_PATH/$CI_COMMIT_BRANCH

stages:
  - build-dev

build:
  stage: build-dev
  script:
    - export NODE_OPTIONS=--max-old-space-size=4096
    - cd $GIT_CLONE_PATH && bun install
    - cd $GIT_CLONE_PATH && bun run build
    - sudo cp /home/weenggs-snehmilan-api/htdocs/community-app-backend.env $GIT_CLONE_PATH/.env
    - sudo chown gitlab-runner:gitlab-runner $GIT_CLONE_PATH/.env
    - |
      if pm2 describe community-app-backend-dev > /dev/null
      then
        echo "The process is already running, so restarting..."
        pm2 restart community-app-backend-dev --time
      else
        echo "The process is not running, starting..."
        pm2 start "bun run start" --name community-app-backend-dev --time
      fi
    - pm2 save
  only:
    - dev
  tags:
    - weenggs-vm-102
  when: manual