import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en_US: {
    translation: {
      description:
        "To retrieve your password, please enter your email or mobile number.",
      submit: "Submit",
      reset: "Reset",
      message:
        "If your village, residential, or business category is not included, please provide the necessary information or blog to us via WhatsApp.",
      contact_details: "For More Details Contact:",
      developed_by: "Design and Developed by",
      think_make: "THINK ! MAKE !",
      login: "Login",
      New_User: "New User?",
      Register: "Register",
      email_label: "Email *",
      email_placeholder: "Enter your email",
      password_label: "Password *",
      password_placeholder: "Enter your password",
      forgot_password: "Forgot Password?",
      or: "** OR **",
      new_registration: "Click Here for New Registration",
      app_helpline: "Application Helpline",
      error_email: "Please enter your email",
      error_password: "Please enter your password",
      forgot_password_title: "Forgot Password?",
      forgot_password_instruction:
        "To retrieve your password, enter your email or mobile number.",
      email_label_id: "Email ID *",
      email_placeholder_mobile_number: "Enter only mobile number",
      app_helpline_title: "Application Helpline",
      helpline_description:
        "If your business category is not included, please provide necessary suggestions to us via\nWhatsapp:",
      contact_info: "For more details, contact:",
      village_Name: "Umrala Village",
      mobile: "Mobile *",
      otp_label: "OTP *",
      error_otp: "Enter the complete OTP",
      submit_button: "Click Here to Login",
      didnt_receive: "Didn't receive the verification OTP?",
      resend_otp: "Resend OTP",
      Already_have_an_account: "Already have an account?",
      Valid_Mobile_no: "Enter your Valid Mobile Number",
      Village_Name: "Village Name",
      Member_list: "Member List",
      Family_Representative: "Family Representative",
      Family_Committee: "Family Committee",
      Find_Member: "Find Member",
      SnehMilan_Pic: "SnehMilan Pic",
      MarkSheet_Upload: "Upload Marksheet",
      Donors: "Donors",
      Golden_Gems: "Golden Gems",
      Events: "Other News",
      WeddingNews: "Wedding News",
      Offer: "Offer",
      Family_Office: "Family Office",
      Photos: "Photos",
      Change_password: "Change Password",
      Helpline_call: "Application Helpline",
      setting: "Settings",
      Log_out: "Logout",
      privacy: "Privacy Policy",
      term_Condition: "Terms & Conditions",
      name: "First Name *",
      fatherName: "Father / Husband's Name *",
      surname: "Surname *",
      gender: "Gender *",
      dob: "Date of Birth",
      address: "Address *",
      email: "Email ID",
      password: "Password *",
      phone: "Mobile Number",
      occupation: "Occupation",
      businessField: "Select Business Field ",
      businessDetails: "Business Details",
      relationship: "relationship ",
      education: "Education",
      bloodGroup: "Blood Group",
      village: "Village *",
      residence: "Residence *",
      maritalStatus: "Marital Status *",
      idProof: "Upload Your ID Proof",
      termsAndConditions: "Terms and Conditions / Privacy Policy",
      addEvent: "Add Event",
      Title: "Title",
      relation: "Relation *",
      Description: "Description",
      eventAddress: "Event Address",
      eventDateTime: "Event Date & Time",
      latitude: "Latitude",
      longitude: "Longitude",
      photoVideoUrl: "Photo/Video URL",
      Submit: "Submit",
      submitting: "Submitting...",
      eventAddedSuccess: "Event added successfully",
      eventAddFailed: "Failed to add event",
      serverError: "Server error:",
      noResponse: "No response from server. Check your network connection.",
      delete_my_Account: "Delete My Account",
      NewMembers: "New Members",
      ReceivedMarksheets: "Received Marksheets",
      FindMarksheet: "Find Marksheet",
      other: "Other",
      business: "Business",
      job: "Job",
      jobField: "Job",
      idproof: "Add your ID proof",
      uploadidprrof: " Upload your ID proof in image format",
      addmember: "Add Member",
      editprofile: "Edit Profile",
      doyouaddmember: "Do you want to add a member of your household?",
      yes: "Yes",
      no: "No",
      Logout: "Logout",
      logout: "Are you sure you want to logout?",
      ok: "OK",
      cancel: "Cancel",
      chooseyourlanguage: "Choose your language",
      Student: "Student",
      delete: "Delete",
      DeleteAccount: "Delete Account",
      DeleteNote:
        "Are you sure you want to delete your account? This action is irreversible.",
      city1: "City",
      country: "Country",
      "Go back": "Go back",
      "Failed to fetch business details": "Failed to fetch business details",
      "Are you sure you want to delete this business?":
        "Are you sure you want to delete this business?",
      "Business deleted successfully": "Business deleted successfully",
      "Failed to delete business": "Failed to delete business",
      "Business not found": "Business not found",

      //admin
      adminprofile: "Admin Profile",
      adminPanel: "Admin Panel",
      users: "Users",
      dashboard: "Dashboard",
      loginasadmin: "Login as admin",
      varification: "Admin Varification",

      table: {
        id: "ID",
        firstname: "First Name",
        middlename: "Middle Name",
        lastname: "Last Name",
        mobilenumber: "Mobile Number",
      },
      adminTitle: {
        villageName: "Umrala Village",
      },
      button: {
        addUser: "Add User",
        submit: "Submit",
        login: "Login",
      },
      label: {
        mobile: "Mobile",
        otp: "OTP",
        notreceive: "OTP didn't receive? ",
      },
      placeholder: {
        enterNumber: "Enter Your Mobile Number",
      },
      error: {
        mobile: "Mobile number required",
        validmobile: "Please enter valid mobile number",
        enterMobile: "Please enter mobile number",
        otperror: "OTP Error",
        invalidotp: "Invalid OTP",
      },
      footer: {
        helpline: "Application Helpline",
      },

      MemberList: {
        Name: "Name",
        FamilyNo: "Family No",
        Relation: "No. of Members",
        totalFamilymember: "Total Families: ",
        totalMembers: "Total Members: ",
      },
      FamilyMembers: {
        address: "Address",
        phone: "Phone",
        email: "Email",
      },
      donors: {
        year: "Year",
        mobile_no: "Mobile Number",
        lifetime_donor: "Lifetime Donor",
        title: "Are you sure?",
        message:
          "Do you really want to delete this donor? This action cannot be undone.",
        cancel: "Cancel",
        delete: "Delete",
        No_Donors_Found: "No Donors Found.",
        add_new: "Add New Donor",
        name: "Name *",
        enter_name: "Enter donor name",
        enter_mobile: "Enter your mobile number",
        donation_category: "Donation Category",
        life_time_donor: "Life Time",
        one_time_donor: "One Time Donor",
        donation_year: "Donation Year",
        alldonors: "All",
        enter_year: "Enter year to donate",
        submit: "Submit",
        submitting: "Submitting...",
        members_list: "Members List",
        no_data: "No data available",
        phone_number: "Phone Number",
        select_type: "Select Donor Type",
        close: "Close",
        save: "Save",
        enteryear: "Enter year",
        profile_picture: "Donor Profile picture",
        donor_type: "Donor Type",
        BhojanSamarambh: "ભોજન સમારંભ",
        InamVitran: "ઇનામ વિતરણ",
        Select_Option: "Select Option",
        Search_Member: "Search Member",
        New_Donor: "New Donor",
        Close: "Close",
        Profile_photo: "Profile Photo",
        addyourprofile: "Add your profile",
        uploadimage: "Upload your profile in image format",
      },

      albumphotos: {
        album_photos: "Album Photos",
        myphotos: "My Photos",
        album: "Album",
        takeselfie: "Take Selfie",
        Noselfiefound: "No selfie photos found",
        selfierelatedphoto: "Selfie Related Photo",
        Nophotofound: "No photos found",
        Nofileselected: "No photos selected",
        Upload: "Upload",
        uploadphotos: "Upload Photos",
        selfieimage: "Selfie Image",
        selectoption: "Select Option",
        deleteselfie: "Delete Selfie",
        deleteconfirmation: "Are you sure you want to delete this selfie?",
        selectselfie: "Select a selfie to view related photos",
      },

      Album: {
        Album: "Album",
        EnterAlbumName: "Enter Album Name",
        selectYear: "Select Year",
        CreateAlbum: "Create Album",
      },
      CommitteeMembers: {
        phone_number: "Phone Number",
      },
      committee: {
        designation: "designation",
        assign_designation: "assign for designation",
        members_list: "Committee Members List",
        update: "Update",
        cancel: "Cancel",
        submit: "Submit",
        president: "President",
        vice_president: "Vice President",
        secretary: "Secretary",
        joint_secretary: "Joint Secretary",
        committee_member: "Committee Member",
        SelectDesignation: "Select Designation",
      },
      title: {
        Registration: "Add New Member",
        RegisterPage: "RegisterPage",
        AwardEligiblestudent: "Award-eligible Students",
        Member_list: "Member List",
        Family_Members: "Family Members",
        FamilySupport: "Family Support",
        village_Name: "Umrala Village",
        News: "News",
        Family_Ads: "Family Ads",
        search_member: "Search Members",
        snehmilan_photo: "Gallery",
        Events: "Events",
        Committee: "Committee Members",
        GoldenGems: "Golden gems",
        received_marksheets: "Received Marksheets",
        new_members: "New Members",
        Bussiness: "Business",
      },
      placeholders: {
        name: "Enter your first name",
        fatherHusbandName: "Enter your father or husband's name",
        address: "Enter your address",
        email: "Enter your email ID",
        password: "Enter your password",
        phone: "Enter your mobile number",
        businessDetails: "Enter details about your business",
        businessField: "Select your business field",
        relationship: "Select your relationship",
        education: "Select your education",
        bloodGroup: "Select your blood group",
        village: "Select your village",
        residence: "Select your residence",
        maritalStatus: "Select your marital status",
        firstName: "Enter your first name",
        middleName: "Enter your Middle Name",
        surname: "Enter your surname",
        numberOfFamilyMembers: "Enter number of family members",
        year: "Year",
        Education: "Education",
        Medium: "Medium",
        other: "Other occupation",
        stream: "Stream",
        standard: "Standard",
        job: "Select your job field ",
        NoOfFamilyMembers: "No of Family Members",
        GeneratePDF: "Generate PDF",
        error: "Please select both year and standard.",
      },
      profileDetails: {
        title: "Profile Details",
        firstName: "First Name *",
        middleName: "Middle Name *",
        surname: "Surname *",
        gender: "Gender *",
        male: "Male",
        female: "Female",
        job: "job",
        business: "Business",
        Other: "Other",
        Nofm: "Number of Family Members *",
      },
      notifications: {
        title: "Notifications",
        all: "All",
        unread: "Unread",
        markallasread: "Mark all as read",
        read: "Read",
        empty: "You've caught up! No unread notifications.",
        emptyniche: "Check back later for new updates.",
      },
      errors: {
        firstName: "First name is required.",
        lastName: "Last name is required.",
        middleName: "Middle Name is required.",
        surname: "Surname is required.",
        surnamee: "Enter number of family members is required.",
        numberOfFamilyMembers: "Enter number of family members  is required.",
        gender: "Please select your gender.",
        required: "This field is required",
        invalidPhone: "Please enter a valid 10-digit phone number",
        invalidEmail: "Please enter a valid email address",
        failedToFetchData: "Failed to fetch data",
        somethingWentWrong: "Something went wrong",
        invalidImageFormat: "Please upload only JPEG, JPG or PNG images",
        fileTooLarge: "File size should be less than 5MB",
      },
      marksheet: {
        uploadInstructions: "Upload Marksheet Instructions :-",
        clear_and_visible: " Marksheet should be clear and visible.",
        readable_info: " Ensure Name, Standard, and Percentage are readable.",
        no_folded_marksheet: "Do not upload folded or crumpled marksheets.",
        good_lighting:
          " Good lighting is required, avoid dark or blurry images.",
        upload_marksheet: "Upload Marksheet",
        title: "Upload Marksheet",
        details: "Marksheet Details",
        name: "Name:",
        percentage: "Percentage:",
        edit: "Edit",
        save: "Save",
        noFile: "No file uploaded",
        preview: "Marksheet Preview",
        goBack: "Go Back",
        no_marksheets_available: "No marksheets available",
        student_name: "Student Name",
        standard: "Standard",
        stream: "Stream",
        medium: "Medium",
        not_available: "Not Available",
        not_specified: "Not Specified",
        marksheet_year: "Marksheet Year",
        your_marksheet_status: "Your Marksheet Status",
        marksheets_available: "No marksheets available.",
        marksheet_status: "No marksheets match your filter criteria.",
      },
      marksheetDetails: {
        title: "Marksheet Details",
        fathername: "Father's Full Name",
        fathernumber: "Father's Mobile Number",
        selectstanderd: "Select Standard",
        EnterPercentage: "Enter Percentage (e.g. 99.63)",
        SelectMedium: " Select Medium",
        SelectYear: "Select Year",
        EnterFatherNumber: "Enter 10-digit phone number",
        EnterFatherName: "Enter Father's Full Name",
        EnterStudentName: "Enter Student Name",
        SelectStream: "Select Stream",
        Findmarksheet: "Find Marksheet",
      },

      news: {
        title: "Notice Board",
        addNews: "Add Notice",
        noNews: "No news found",
        confirmDelete: "Confirm Delete",
        deleteMessage:
          "Are you sure you want to delete this news item? This action cannot be undone.",
        cancel: "Cancel",
        delete: "Delete",
        loading: "Loading...",
        errorLoading: "Failed to load news. Please try again later.",
        errorDeleting: "Failed to delete news. Please try again.",
        communityNews: "Community News",
        newstitle: "Title",
        description: "Description",
        type: "Notice Type",
        AddNews_title: "Add Notice",
        successMessage: "Notice added successfully!",
        errorMessage: "An error occurred. Please try again.",
        photo: "Photo",
        cardtitle: "Title",
        news: "Notice",
        maran_nondh: "Maran Nondh",
        newslist: "Notice List",
        descriptionnote: "Add Description",
        deletewarning: "Are you sure you want to delete this news item?",
        uploadimage: "Upload Image",
        changeimage: "Change Image",
        noMoreNews: "No more news available",
        types: {
          news: "ગામ ના સમાચાર",
          maran_nondh: "અવસાન નોંધ",
        },
      },

      buttons: {
        submit: "Register",
        skip: "Skip",
        addEvent: "Add Event",
        cancel: "Cancel",
        delete: "Delete",
      },
      labels: {
        upcomingEvents: "Upcoming Events",
        eventDate: "Event Date",
        eventAddress: "Event Address",
      },
      messages: {
        requiredField: "This field is required.",
        uploadIdProof: "Aadhaar card, license, or others...",
        noEvents: "No events found. Be the first to add an event!",
        deleteConfirm:
          "Are you sure you want to delete this event? This action cannot be undone.",
        deleteError: "Failed to delete event. Please try again later.",
      },
      app: {
        communityApp: "Community App",
      },
      received_marksheets: {
        title: "all Marksheet",
        name: "Name:",
        percentage: "Percentage:",
        save: "Save",
        no_marksheets_available: "No marksheets available",
        student_name: "Student Name",
        standard: "Standard",
        stream: "Stream",
        medium: "Medium",
        marksheet_year: "Marksheet Year",
      },
      abroadMembers: {
        Abroad_Members: "Abroad Members",
        Designation: "Designation",
        Experience: "Experience",
        years: "years",
        No_abroad_members_found: "No abroad members found",
        Confirm_Delete: "Confirm Delete",
        delete_member: "Are you sure you want to delete this member?",
        Delete: "Delete",
        Cancel: "Cancel",
        abroad_members: "Error fetching abroad members",
        loading_admin: "Error loading admin data",
        Member_deleted_successfully: "Member deleted successfully!",
        deleting_member: "Error deleting member",
        fullName: "Full Name *",
        enterfirstName: "* Write the surname first",
        passportPhoto: "Profile Photo *",
        uploadPhoto: "Upload Your Profile Photo",
        remove: "Remove",
        workSector: "Work Sector",
        government: "Government",
        private: "Private",
        designation: "Designation/Position *",
        designationeg:
          "* If you are a student, doctor, lawyer, IT, CA, entrepreneur, or in a government job, write accordingly",
        career: "Career",
        careereg: "* Writing down the details of the study",
        experience: "Years of Experience",
        contactNumber: "Contact Number *",
        internationalCode:
          "* Please send your contact number with the international code and your name to 9427140686 (e.g., +427140686)",
        country: "Country *",
        countryeg: "* The name of the country you are currently in",
        city: "City *",
        cityeg: "* The name of the city you are currently in",
        successMantra: "Success Mantra",
        successMantraDescription:
          "* Share your motivational mantra for success",
        thoughtsOnCommittee: "Thoughts on Committee Work",
        thoughtsOnCommitteeDescription:
          "* Share your feedback and suggestions regarding committee work",
        submitButton: "Add Member",
        updateButton: "Update Member",
        editTitle: "Edit Abroad Member",
        addTitle: "Add Abroad Member",
        validationError: "Validation error",
        loadingError: "Error loading member data",
        memberAddedSuccess: "Member added successfully!",
        memberUpdatedSuccess: "Member updated successfully!",
        formSubmissionError: "Error updating/creating member",
        notifyError: "Error loading member data",
        submitError: "Form submission error",
        validation: {
          fullNameRequired: "Full name is required",
          passportPhotoRequired: "Passport photo is required",
          designationRequired: "Designation is required",
          contactNumberRequired: "Contact number is required",
          invalidContactNumber: "Please enter a valid contact number",
          countryRequired: "Country is required",
          cityRequired: "City is required",
          experienceNumberOnly: "Experience must be a number",
        },
      },
      details: {
        title: "Details",
        gender: "Gender",
        blood_group: "Blood Group",
        marital_status: "Marital Status",
        family_members: "Family Members",
        occupation: "Occupation",
        relationship: "Relationship",
        address: "Address",
        CurrentResident: "Current Resident",
        EnterCity: "Enter City",
        phone: "Phone",
        education: "Education",
        email: "Email",
        business_field: "Business Field",
        date_of_birth: "Date of Birth",
        community_admin: "Community Admin",
        id_proof: "ID Proof",
        no_id_proof: "No ID Proof",
      },
      professionaldetails: {
        title: "Professional Details",
        employment_type: "Employment Type",
        experience_years: "Experience (Years)",
        location: "Location",
        designation: "Designation",
        phone: "Phone",
        career: "Career",
        success_mantra: "Success Mantra",
        thoughts_on_committee: "Thoughts on Committee",
      },
      awardstudents: {
        filterPrompt: "Please select at least one filter to view students.",
        noStudentsFound: "No students found matching the selected criteria.",
        standard: "Standard",
        medium: "Medium",
        stream: "Stream",
        percentage: "Percentage",
        year: "Year",
      },
      Business2: {
        details: "Business Details",
        phone: "Phone Number",
        email: "Email Address",
        address: "Address",
        location: "Location",
        category: "Category",
        business_type: "Business Type",
        name: "Business Name",
        enterName: "Enter business name",
        city: "City",
        enterCity: "Enter city name",
        state: "State",
        enterAddress: "Enter complete business address",
        contact: "Contact Number",
        enterContact: "Enter 10-digit mobile number",
        enterEmail: "Enter email address",
        type: "Business Type",
        photo: "Business Photo",
        uploadPhoto: "Upload Business Photo",
        changePhoto: "Change Business Photo",
        logo: "Business Logo",
        uploadLogo: "Upload Business Logo",
        changeLogo: "Change Business Logo",
        remove: "Remove",
        addBusiness: "Add Business",
        editBusiness: "Edit Business",
        addSuccess: "Business added successfully",
        updateSuccess: "Business updated successfully",
        No_business_found: "No business found",
        services_products: "Services/Products",
      },
    },
  },
  gu_IN: {
    translation: {
      description:
        "તમારું પાસવર્ડ મેળવવા માટે, તમારું ઈમેઇલ અથવા મોબાઇલ નંબર દાખલ કરો.",
      mobile: "મોબાઈલ નંબર *",
      email_mobile: "તમારું મોબાઈલ નંબર લખો",
      submit: "ઓટીપી મોકલો",
      reset: "રદ કરો",
      message:
        "તમારા ગામ, રહેણાંક કે વ્યવસાય ક્ષેત્ર કેટેગરી માં ન હોય તો જરૂરી માહિતી કે બ્લોગ આપવા માટે વોટ્સએપ કરો.",
      contact_details: "વધુ વિગત માટે સંપર્ક કરો:",
      developed_by: "ડિઝાઇન અને વિકાસકર્તા",
      think_make: "વિચાર કરો ! બનાવો !",
      login: "લોગિન",
      New_User: "નવા વપરાશકર્તા?",
      Register: "નોંધણી કરો",
      email_label: "ઇમેઇલ *",
      fatherName: "પિતા / પતિનું નામ *",
      surname: "અટક *",
      email_placeholder: "તમારું ઇમેઇલ લખો",
      password_label: "પાસવર્ડ *",
      password_placeholder: "તમારું પાસવર્ડ લખો",
      forgot_password: "પાસવર્ડ ભૂલાઈ ગયો છે?",
      or: "** અથવા **",
      new_registration: "નવી નોંધણી માટે અહીં ક્લિક કરો",
      app_helpline: "એપ્લિકેશન હેલ્પલાઇન",
      error_email: "ઇમેઇલ લખો",
      error_password: "પાસવર્ડ લખો ",
      forgot_password_title: "પાસવર્ડ ભૂલી ગયા છો?",
      forgot_password_instruction:
        "તમારું પાસવર્ડ મેળવવા માટે, તમારું ઈમેઇલ અથવા મોબાઈલ નંબર દાખલ કરો.",
      email_label_id: "ઇમેઇલ આઇડી *",
      email_placeholder_mobile_number: "તમારું મોબાઈલ નંબર લખો",
      app_helpline_title: "એપ્લિકેશન હેલ્પલાઇન",
      helpline_description:
        "જો તમારા વ્યવસાયની શ્રેણી શામેલ નથી, તો કૃપા કરીને Whatsapp દ્વારા અમને જરૂરી સૂચનો આપો:",
      contact_info: "વધુ વિગતો માટે સંપર્ક કરો:",
      otp_label: "ઓટિપિ *",
      error_otp: "પુરો ઓટિપિ દાખલ કરો",
      submit_button: "લોગિન માટે ક્લિક કરો",
      didnt_receive: "ઓટિપિ મળ્યો નથી?",
      resend_otp: "ફરીથી ઓટિપિ મોકલો",
      Already_have_an_account: "પહેલેથી જ એક એકાઉન્ટ છે?",
      Valid_Mobile_no: "તમારું માન્ય મોબાઈલ નંબર દાખલ કરો",
      Village_Name: "ગામનું નામ",
      Member_list: "સભ્યોની યાદી",
      Family_Representative: "પરિવાર પ્રતિનિધિ",
      Family_Committee: "પરિવાર કમિટી",
      Find_Member: "સભ્ય શોધ",
      SnehMilan_Pic: "સ્નેહમિલન તસવીર",
      MarkSheet_Upload: "માર્કશીટ અપલોડ",
      Donors: "દાતાશ્રીઓ",
      Golden_Gems: "સુવર્ણ રત્નો",
      Events: "અન્ય સમાચાર",
      WeddingNews: "લગ્ન સમાચાર",
      Change_password: "પાસવર્ડ બદલવા માટે",
      Family_Office: "પરિવારનું કાર્યાલય",
      Photos: "ફોટો ગેલેરી",
      Helpline_call: "એપ્લિકેશન  હેલ્પલાઇન",
      Offer: "ઓફર",
      setting: "સેટિંગ્સ",
      Log_out: "લોગ આઉટ",
      privacy: "પ્રાઇવસી પોલિસી",
      term_Condition: "ટર્મ્સ & કન્ડિશન",
      name: "નામ *",
      fatherHusbandName: "પિતા / પતિ નું નામ *",
      gender: "જાતિ *",
      dob: "જન્મદિવસ તારીખ *",
      address: "સરનામું *",
      email: "ઈમેલ આઈડી *",
      password: "પાસવર્ડ *",
      phone: "મોબાઈલ નંબર *",
      occupation: "ધંધો *",
      businessField: "વ્યવસાય ક્ષેત્રે પસંદ કરો *",
      businessDetails: "વ્યવસાય વિગતો",
      relationship: "સબંધ",
      relation: "સબંધ",
      education: "શિક્ષણ",
      bloodGroup: "રક્ત જૂથ",
      village: "ગામ *",
      residence: "રહેણાંક *",
      maritalStatus: "લગ્ન દરજ્જો *",
      idProof: "તમારું આઇડી પુરાવો ઉમેરો",
      termsAndConditions: "નિયમો અને શરતો / પ્રાઇવસી પોલિસી",
      addEvent: "ઈવેન્ટ ઉમેરો",
      Title: "શીર્ષક",
      Description: "વર્ણન",
      eventAddress: "ઇવેન્ટ સરનામું",
      eventDateTime: "ઇવેન્ટ તારીખ અને સમય",
      latitude: "અક્ષાંશ",
      longitude: "રેખાંશ",
      photoVideoUrl: "ફોટો/વિડિઓ URL",
      Submit: "સબમિટ કરો",
      submitting: "સબમિટ કરી રહ્યું છે...",
      eventAddedSuccess: "ઇવેન્ટ સફળતાપૂર્વક ઉમેરાઈ",
      eventAddFailed: "ઇવેન્ટ ઉમેરવામાં નિષ્ફળ",
      serverError: "સર્વર ભૂલ:",
      noResponse:
        "સર્વર તરફથી કોઈ પ્રતિસાદ મળ્યો નથી. તમારું નેટવર્ક કનેક્શન તપાસો.",
      delete_my_Account: "એકાઉન્ટ ડીલીટ કરો",
      NewMembers: "નવા સભ્ય",
      ReceivedMarksheets: "મેળવેલ માર્કશીટ",
      FindMarksheet: "માર્કશીટ શોધો",
      other: "અન્ય",
      business: "વ્યવસાય",
      job: "જોબ",
      idproof: "તમારું આઈડી પુરાવો ઉમેરો",
      uploadidprrof: "તમારો આઈડી પુરાવો ફોટોના સ્વરૂપમાં અપલોડ કરો",
      addmember: "સભ્ય ઉમેરો",
      editprofile: "એડિટ પ્રોફાઇલ",
      doyouaddmember: "શું તમે તમારા પરિવારના સભ્યને ઉમેરવા માંગો છો?",
      yes: "હા",
      no: " ના",
      logout: "શું તમે ખરેખર લોગ આઉટ કરવા માંગો છો?",
      ok: "ઓકે",
      cancel: "રદ કરો",
      Logout: "લોગ આઉટ",
      chooseyourlanguage: "તમારી ભાષા પસંદ કરો",
      jobField: "જોબ ક્ષેત્ર",
      Student: "વિદ્યાર્થી",
      delete: "કાઢી નાખો",
      DeleteAccount: "એકાઉન્ટ કાઢી નાખો",
      DeleteNote:
        "તમારા એકાઉન્ટને સંપૂર્ણપણે કાઢી નાખવામાં આવશે. શું તમે ખાતરી કરો છો કે તમે તમારા એકાઉન્ટને કાઢી નાખવા માંગો છો?",
      selectselfie: "સંબંધિત ફોટા જોવા માટે સેલ્ફી પસંદ કરો",
      deleteconfirmation: "શું તમે ખરેખર આ સેલ્ફી કાઢી નાખવા માંગો છો?",
      city1: "શહેર",
      country: "દેશ",
      "Go back": "પાછા જાઓ",
      "Failed to fetch business details": "વ્યવસાયની વિગતો મેળવવામાં નિષ્ફળ",
      "Are you sure you want to delete this business?":
        "શું તમે ખરેખર આ વ્યવસાય કાઢી નાખવા માંગો છો?",
      "Business deleted successfully": "વ્યવસાય સફળતાપૂર્વક કાઢી નાખ્યો",
      "Failed to delete business": "વ્યવસાય કાઢી નાખવામાં નિષ્ફળ",
      "Business not found": "વ્યવસાય મળ્યો નથી",

      //admin
      adminprofile: "એડમિન પ્રોફાઇલ",
      adminPanel: "એડમિન પેનલ",
      users: "વપરાશકર્તાઓ",
      dashboard: "ડેશબોર્ડ",
      loginasadmin: "એડમિન તારિકે લૉગિન ",
      varification: "એડમિન ચકાસણી",

      MemberList: {
        Name: "નામ",
        FamilyNo: "કુટુંબ નંબર",
        Relation: "સભ્ય સંખ્યા",
        totalFamilymember: "પરિવાર ની કુલ સંખ્યા:",
        totalMembers: "કુલ સભ્યો:",
      },
      FamilyMembers: {
        address: "સરનામું",
        phone: "ફોન",
        email: "ઈમેલ",
      },
      donors: {
        year: "વર્ષ",
        mobile_no: "મોબાઇલ નંબર ",
        ifetime_donor: "જીવન સમય દાતા છે",
        title: "શું તમે ખાતરી કરો છો?",
        message:
          "શું તમે ખરેખર આ દાતાને કાઢી નાખવા માંગો છો? આ ક્રિયા પાછી લાવી શકાતી નથી.",
        cancel: "રદ કરો",
        delete: "કાઢી નાખો",
        No_Donors_Found: "કોઈ દાતાશ્રી મળી નથી",
        add_new: "નવી દાનશીલો ઉમેરો",
        name: "નામ",
        enter_name: "દાનશીલોનું નામ દાખલ કરો",
        enter_mobile: "તમારો મોબાઇલ નંબર દાખલ કરો ",
        donation_category: "દાન શ્રેણી *",
        life_time_donor: "આજીવન",
        one_time_donor: "એક વખત દાતાશી",
        donation_year: "દાન વર્ષ",
        alldonors: "બધા",
        enter_year: "દાન વર્ષ દાખલ કરો",
        submit: "સબમિટ કરો",
        submitting: "સબમિટ થઈ રહ્યું છે...",
        members_list: "સભ્યોની યાદી",
        no_data: "કોઈ ડેટા ઉપલબ્ધ નથી",
        phone_number: "ફોન નંબર",
        select_type: "દાનશી પ્રકાર પસંદ કરો",
        close: "બંધ કરો",
        save: "સેવ",
        enteryear: "વર્ષ દાખલ કરો",
        profile_picture: "દાતાશી પ્રોફાઇલ ચિત્ર",
        donor_type: "દાનશી પ્રકાર",
        BhojanSamarambh: "ભોજન સમારંભ",
        InamVitran: "ઇનામ વિતરણ",
        Select_Option: "વિકલ્પ પસંદ કરો",
        Search_Member: "સભ્ય શોધો",
        New_Donor: "નવા દાતા",
        Close: "બંધ કરો",
        Profile_photo: "પ્રોફાઇલ ફોટો",
        addyourprofile: "તમારો પ્રોફાઇલ ફોટો ઉમેરો",
        uploadimage: "તમારો આઈડી પુરાવો ફોટોના સ્વરૂપમાં અપલોડ કરો",
      },

      CommitteeMembers: {
        phone_number: "ફોન નંબર",
      },
      committee: {
        designation: "હોદ્દો",
        assign_designation: "હોદ્દો માટે નિયુક્ત કરો",
        members_list: "સમિતિ સભ્યોની યાદી",
        update: "અપડેટ કરો",
        cancel: "રદ કરો",
        submit: "સબમિટ કરો",
        president: "પ્રમુખ",
        vice_president: "ઉપ પ્રમુખ",
        secretary: "મંત્રી",
        joint_secretary: "સહ મંત્રી",
        committee_member: "કમીટી સભ્ય",
        SelectDesignation: "હોદ્દો પસંદ કરો",
      },
      albumphotos: {
        album_photos: "આલ્બમ ફોટા",
        myphotos: "મારા ફોટા",
        album: "આલ્બમ",
        takeselfie: "સેલ્ફી લો",
        Noselfiefound: "કોઈ સેલ્ફી ફોટા મળ્યા નથી",
        selfierelatedphoto: "સેલ્ફી સંબંધિત ફોટા",
        Nophotofound: "કોઈ ફોટા મળ્યા નથી",
        Nofileselected: "કોઈ ફાઇલ પસંદ કરેલ નથી",
        Upload: "અપલોડ કરો",
        uploadphotos: "અપલોડ ફોટા",
        selfieimage: "સેલ્ફી ફોટા",
        selectoption: "પસંદગી પસંદ કરો",
        deleteselfie: "સેલ્ફી કાઢી નાખો",
        deleteconfirmation: "શું તમે ખરેખર આ સેલ્ફી કાઢી નાખવા માંગો છો?",
      },
      Album: {
        Album: "આલ્બમ",
        EnterAlbumName: "આલ્બમ નામ દાખલ કરો",
        selectYear: "વર્ષ પસંદ કરો",
        CreateAlbum: "આલ્બમ બનાવો",
      },
      table: {
        id: "આઈડી",
        firstname: "પ્રથમ નામ",
        middlename: "પિતા નુ નામ",
        lastname: "અટક",
        mobilenumber: "મોબાઇલ નંબર",
      },
      adminTitle: {
        villageName: "ઉમરાળા ગામ",
      },
      button: {
        addUser: "વપરાશકર્તા ઉમેરો",
        submit: "સબમિટ કરો",
        login: "લૉગિન",
      },
      label: {
        mobile: "મોબાઇલ",
        otp: "ઓટીપી",
        notreceive: "ઓટીપી મળ્યો નથી? ",
      },
      placeholder: {
        enterNumber: "મોબાઇલ નંબર દખાલ કરો",
      },
      error: {
        mobile: "મોબાઇલ નંબર જરૂરી",
        validmobile: "કૃપા કરીને માન્ય મોબાઇલ નંબર દાખલ કરો.",
        otperror: "ઓટીપી ભૂલ",
        invalidotp: "અમાન્ય ઓટીપી",
        enterMobile: " તમારો મોબાઇલ નંબર દાખલ કરો.",
      },
      footer: {
        helpline: "એપ્લીકેશન હેલ્પલાઇન",
      },

      title: {
        Registration: "નવા વપરાશકર્તા",
        RegisterPage: "નવા વપરાશકર્તા",
        AwardEligiblestudent: "ઇનામ ને પાત્ર વિદ્યાર્થીઓ",
        VillageList: "ગામની યાદી",
        Member_list: "સભ્યોની યાદી",
        Family_Members: "પરિવારના સભ્યો",
        FamilySupport: "કુટુંબ આધાર",
        village_Name: "ઉમરાળા ગામ",
        News: "નોકરી ના સમાચાર",
        Family_Ads: "કુટુંબ જાહેરાતો",
        search_member: "શોધ સભ્ય",
        snehmilan_photo: "ફોટા",
        Events: "અન્ય સમાચાર",
        Committee: "કમિટી સભ્યો",
        GoldenGems: "સુવર્ન રાત્નો",
        received_marksheets: "મેળવેલ માર્કશીટ",
        new_members: "નવા સભ્ય",
        Bussiness: "વ્યવસાય",
      },
      notifications: {
        title: "નોટિફિકેશન",
        all: "બધા",
        unread: "વાંચ્યા વગરનું",
        markallasread: "બધા વાંચો",
        read: "વાંચ્યું",
        empty: "કોઈ વાંચ્યા વગરની સૂચનાઓ નથી.",
        emptyniche: "નવા અપડેટ્સ માટે પછીથી ફરી તપાસ કરો.",
      },
      placeholders: {
        name: "તમારું નામ લખો",
        fatherHusbandName: "માત્ર તમારાં પિતા / પતિ નું નામ લખો",
        address: "સરનામું લખો",
        email: "ઈમેલ આઈડી લખો",
        password: "પાસવર્ડ લખો",
        phone: "મોબાઈલ નંબર લખો",
        businessDetails: "વ્યવસાય વિગત લખો",
        businessField: "વ્યવસાય ક્ષેત્રે પસંદ કરો",
        relationship: "સબંધ પસંદ કરો",
        education: "શિક્ષણ",
        bloodGroup: "રક્ત જૂથ પસંદ કરો",
        village: "તમારું ગામ પસંદ કરો",
        residence: "તમારું રહેણાંક પસંદ કરો",
        maritalStatus: "તમારી લગ્નની સ્થિતિ પસંદ કરો",
        firstName: "તમારું પ્રથમ નામ દાખલ કરો",
        middleName: "તમારા પિતા નું નામ દાખલ કરો",
        surname: "તમારી અટક દાખલ કરો",
        numberOfFamilyMembers: "પરિવારના સભ્યોની સંખ્યા દાખલ કરો",
        year: "વર્ષ",
        Education: "શિક્ષણ",
        Medium: "મેડિયમ",
        other: "અન્ય વ્યવસાય",
        stream: "પ્રવાહ",
        standard: "ધોરણ",
        job: "તમારી નોકરીનું ક્ષેત્ર પસંદ કરો",
        NoOfFamilyMembers: "પરિવારના સભ્યોની સંખ્યા",
        GeneratePDF: "પીડીએફ જનરેટ કરો",
        error: "કૃપા કરીને વર્ષ અને ધોરણ બંને પસંદ કરો.",
      },
      profileDetails: {
        title: "પ્રોફાઇલ વિગતો",
        firstName: "પ્રથમ નામ",
        middleName: "પિતા નું નામ",
        surname: "અટક",
        gender: "લિંગ",
        male: "પુરૂષ",
        female: "સ્ત્રી",
        job: "નોકરી",
        business: "ધંધો",
        Other: "અન્ય",
        Nofm: "પરિવારના સભ્યોની સંખ્યા",
      },

      errors: {
        firstName: "પ્રથમ નામ જરૂરી છે.",
        lastName: "છેલ્લું નામ જરૂરી છે.",
        surname: "ઉપનામ જરૂરી છે.",
        numberOfFamilyMembers: "પરિવારના સભ્યોની સંખ્યા જરૂરી છે.",
        gender: "કૃપા કરીને તમારું લિંગ પસંદ કરો.",
        required: "આ ક્ષેત્ર આવશ્યક છે",
        invalidPhone: "કૃપા કરી માન્ય 10-અંકનો ફોન નંબર દાખલ કરો",
        invalidEmail: "કૃપા કરી માન્ય ઈમેલ સરનામું દાખલ કરો",
        failedToFetchData: "ડેટા મેળવવામાં નિષ્ફળ",
        somethingWentWrong: "કંઈક ખોટું થયું",
        invalidImageFormat: "કૃપા કરી ફક્ત JPEG, JPG અથવા PNG ઇમેજ અપલોડ કરો",
        fileTooLarge: "ફાઇલનું કદ 5MB કરતાં ઓછું હોવું જોઈએ",
      },
      marksheet: {
        uploadInstructions: "માર્કશીટ અપલોડ સૂચનાઓ:-",
        clear_and_visible: "માર્કશીટ સાફ અને દેખીતી હોવી જોઈએ.",
        readable_info: "નામ, ધોરણ અને ટકાવારી વાંચી શકાય તેવી હોવી જોઈએ.",
        no_folded_marksheet: "વાંકી અથવા નબળી સ્થિતિની માર્કશીટ અપલોડ ન કરો.",
        good_lighting:
          "સારી લાઈટિંગ જરૂરી છે, અંધકારમય અથવા ધૂંધળી છબીઓથી બચો.",
        upload_marksheet: "માર્કશીટ અપલોડ કરો",
        title: "માર્કશીટ અપલોડ",
        details: "માર્કશીટ વિગતો",
        name: "નામ:",
        percentage: "ટકાવારી:",
        edit: "ફેરફાર કરો",
        save: "સાચવો",
        noFile: "કોઈ ફાઇલ અપલોડ કરી નથી",
        preview: "માર્કશીટ પૂર્વદર્શન",
        goBack: "પાછા જાઓ",
        no_marksheets_available: "કોઈ માર્કશીટ ઉપલબ્ધ નથી",
        student_name: "વિદ્યાર્થીનું નામ",
        standard: "ધોરણ",
        stream: "પ્રવાહ",
        medium: "માધ્યમ",
        not_available: "ઉપલબ્ધ નથી",
        not_specified: "નિર્દિષ્ટ નથી",
        marksheet_year: " માર્કશીટ વર્ષ:",
        your_marksheet_status: "તમારી માર્કશીટની સ્થિતિ",
        marksheets_available: "માર્કશીટ ઉપલબ્ધ નથી",
        marksheet_status:
          "તમે સિલેક્ટ કરેલ ફિલ્ટર સાથે કોઈ માર્કશીટ મેળ ખાતી નથી.",
      },
      marksheetDetails: {
        title: "માર્કશીટ ની વિગતો",
        fathername: "પિતાનું નામ",
        fathernumber: "પિતાનો મોબાઈલ નંબર",
        selectstanderd: "ધોરણ પસંદ કરો",
        EnterPercentage: "ટકાવારી દાખલ કરો (e.g. 99.63)",
        SelectMedium: "માધ્યમ પસંદ કરો",
        SelectYear: "વર્ષ પસંદ કરો",
        EnterFatherName: "પિતાનું નામ દાખલ કરો",
        EnterFatherNumber: "10-અંકનો ફોન નંબર દાખલ કરો",
        EnterStudentName: "વિદ્યાર્થીનું નામ દાખલ કરો",
        SelectStream: "પ્રવાહ પસંદ કરો",
        Findmarksheet: "માર્કશીટ શોધો",
      },
      news: {
        title: "સૂચના બોર્ડ",
        addNews: "સૂચના ઉમેરો",
        noNews: "કોઈ સૂચના મળી નથી.",
        confirmDelete: "હટાવવાની ખાતરી કરો",
        deleteMessage:
          "શું તમે ખરેખર આ સૂચનાને દૂર કરવા માંગો છો? આ ક્રિયા પાછી લાવી શકાય નહીં.",
        cancel: "રદ કરો",
        delete: "હટાવો",
        loading: "લોડ થઈ રહ્યું છે...",
        errorLoading:
          "સૂચના લોડ કરવામાં નિષ્ફળ. મહેરબાની કરીને ફરીથી પ્રયત્ન કરો.",
        errorDeleting:
          "સૂચના કાઢવામાં નિષ્ફળ. મહેરબાની કરીને ફરીથી પ્રયત્ન કરો.",
        communityNews: "સમૂહ સૂચના",
        // descriptionnote: "સૂચનાનું વર્ણન ઉમેરો",
        // AddNews_title: "સૂચના ઉમેરો",
        successMessage: "સૂચના સફળતાપૂર્વક ઉમેરવામાં આવ્યું!",
        errorMessage: "એક ભૂલ આવી. મહેરબાની કરીને ફરીથી પ્રયત્ન કરો.",
        cardtitle: "શીર્ષક",
        // description: "વર્ણન",
        // newstitle: "સૂચનાનું શીર્ષક",
        // type: "સૂચનાનો પ્રકાર",
        newslist: "સૂચનાની યાદી",
        deletewarning: "શું તમે ખરેખર આ સમાચાર આઇટમ કાઢી નાખવા માંગો છો?",
        uploadimage: "ફોટો અપલોડ કરો",
        changeimage: "ફોટો બદલો",
        noMoreNews: "કોઈ વધુ સમાચાર નથી.",
        types: {
          news: "ગામ ના સમાચાર",
          maran_nondh: "અવસાન નોંધ",
        },
      },
      buttons: {
        submit: "નોંધણી કરો",
        skip: "આગળ વધો",
        cancel: "રદ કરો",
        delete: "કાઢી નાખો",
        addEvent: "ઇવેન્ટ ઉમેરો",
      },
      labels: {
        upcomingEvents: "આગામી સમાચાર",
        eventDate: "ઇવેન્ટ તારીખ",
        eventAddress: "ઇવેન્ટનું સરનામું",
      },
      messages: {
        requiredField: "આ ફીલ્ડ જરૂરી છે.",
        uploadIdProof: "આધારકાર્ડ, લાઇસન્સ કે અન્ય...",
        noEvents: "કોઈ ઇવેન્ટ મળ્યું નથી. પહેલો ઇવેન્ટ ઉમેરો!",
        deleteConfirm:
          "શું તમે ખરેખર આ ઇવેન્ટ ડિલીટ કરવા માંગો છો? આ ક્રિયા પાછી લાવી શકાશે નહીં.",
        deleteError:
          "ઇવેન્ટ ડિલીટ કરવામાં નિષ્ફળ. મહેરબાની કરીને પછી ફરી પ્રયાસ કરો.",
      },
      app: {
        communityApp: "કોમ્યુનિટી એપ",
      },
      received_marksheets: {
        Title: "માર્કશીટ",
        name: "નામ:",
        percentage: "ટકાવારી:",
        save: "Save",
        student_name: "વિદ્યાર્થીનું નામ",
        standard: "ધોરણ",
        stream: "પ્રવાહ",
        medium: "માધ્યમ",
        marksheet_year: "માર્કશીટ વર્ષ:",
      },
      abroadMembers: {
        Abroad_Members: "વિદેશના સભ્યો",
        Designation: "વ્યવસાય",
        Experience: "અનુભવ",
        years: "વર્ષ",
        No_abroad_members_found: "કોઈ વિદેશના સભ્યો મળ્યા નથી",
        Confirm_Delete: "મૂલો કાઢવાની પુષ્ટિ કરો",
        delete_member: "શું તમે વાસ્તવમાં આ સભ્યને કાઢી નાખવા માંગો છો?",
        Delete: "કાઢો",
        Cancel: "રદ કરો",
        abroad_members: "વિદેશના સભ્યોને લાવવા માં ખોટો અનુસંધાન",
        loading_admin: "એડમિન ડેટા લોડ કરવામાં ખોટો",
        Member_deleted_successfully: "સભ્ય સફળતાપૂર્વક કાઢી નાખવામાં આવ્યો!",
        deleting_member: "સભ્ય કાઢી નાખવામાં ખોટો",
        fullName: "આપનું પૂરું નામ *",
        enterfirstName: "* અટક પેહલા લખવી .",
        passportPhoto: "આપના પ્રોફાઇલ ફોટો *",
        uploadPhoto: "તમારો પ્રોફાઇલ ફોટો અપલોડ કરો",
        remove: "હટાવો",
        workSector: "આપ ક્યાં ક્ષેત્રમાં છો",
        government: "સરકાર",
        private: "પ્રાઈવેટ",
        designation: "આપનો હોદ્દો *",
        designationeg:
          "* વિદ્યાર્થી, ડોક્ટર,વકીલ,IT,CA,ઉદ્યોગસાહસિક તેમેજ સરકારી નોકરીમાં હોવ તો તે મુજબ લખવું",
        experience: "અનુભવના વર્ષો",
        career: "આપની લાયકાત",
        careereg: "અભ્યાસની વિગતો લખવી",
        contactNumber: "આપનો સંપર્ક નંબર *",
        internationalCode:
          "* કૃપા કરીને તમારા સંપર્ક નંબર સાથે આંતરરાષ્ટ્રીય કોડ અને તમારું નામ 9427140686 પર મોકલો (ઉદાહરણ: +427140686)",
        country: "આપનુ કાર્યક્ષેત્ર દેશ *",
        countryeg: "* જે દેશમાં હાલમાં છો તેનું નામ ",
        city: "આપનુ કાર્યક્ષેત્ર - ગામ, શહેર *",
        cityeg:
          "* જે દેશમાં હાલમાં છો તેના જે ગામ કે શહેરમાં રહો છો તેનું  નામ લખવું",
        successMantra: "આપની સફળતાની વિગતો",
        successMantraDescription:
          "* તમારી સફળતા માટેનો પ્રેરણાત્મક મંત્ર શેર કરો",
        thoughtsOnCommittee: "કમિટી કાર્ય પર વિચારો",
        thoughtsOnCommitteeDescription:
          "* ઉમરાળા ગામ સમસ્ત પટેલ સમાજની પ્રગતિ માટે આપના સૂચનો કે નવા વિચારો",
        submitButton: "મેમ્બર ઉમેરો",
        updateButton: "મેમ્બર અપડેટ કરો",
        editTitle: "વિદેશ મેમ્બર સુધારો",
        addTitle: "વિદેશ મેમ્બર ઉમેરો",
        validationError: "માન્યતા ભૂલ",
        loadingError: "મેમ્બરની ડેટા લોડ કરવામાં સમસ્યા આવી છે",
        memberAddedSuccess: "મેમ્બર સફળતાપૂર્વક ઉમેરાયો!",
        memberUpdatedSuccess: "મેમ્બર સફળતાપૂર્વક અપડેટ થયો!",
        formSubmissionError: "મેમ્બર અપડેટ/બનાવતા સમયે સમસ્યા આવી",
        notifyError: "મેમ્બરની ડેટા લોડ કરવામાં સમસ્યા આવી છે",
        submitError: "ફોર્મ સબમિટ કરવામાં સમસ્યા આવી",

        validation: {
          fullNameRequired: "પૂરું નામ આવશ્યક છે",
          passportPhotoRequired: "પાસપોર્ટ ફોટો આવશ્યક છે",
          designationRequired: "હોદ્દો આવશ્યક છે",
          contactNumberRequired: "સંપર્ક નંબર આવશ્યક છે",
          invalidContactNumber: "કૃપા કરી માન્ય સંપર્ક નંબર દાખલ કરો",
          countryRequired: "દેશ આવશ્યક છે",
          cityRequired: "શહેર આવશ્યક છે",
          experienceNumberOnly: "અનુભવ માટે માત્ર સંખ્યા દાખલ કરો",
        },
      },

      details: {
        title: "વિગતો",
        gender: "જાતિ",
        blood_group: "બ્લડ ગ્રુપ",
        marital_status: "વૈવાહિક સ્થિતિ",
        family_members: "કુટુંબના સભ્યો",
        occupation: "વ્યવસાય",
        relationship: "સબંધ",
        address: "વિસ્તાર",
        CurrentResident: "હાલનો નિવાસ",
        phone: "ફોન",
        education: "શિક્ષણ",
        email: "ઇમેઇલ",
        EnterCity: "શહેર દાખલ કરો",
        business_field: "વ્યવસાય ક્ષેત્ર",
        date_of_birth: "જન્મ તારીખ",
        community_admin: "સમુદાય એડમિન",
        id_proof: "આઇડી પુરાવો",
        no_id_proof: "કોઈ આઇડી પુરાવો નથી",
      },
      professionaldetails: {
        title: "વ્યાવસાયિક વિગતો",
        employment_type: "રોજગાર પ્રકાર",
        experience_years: "અનુભવ (વર્ષ)",
        location: "સ્થાન",
        designation: "પદવી",
        phone: "ફોન",
        career: "કેરિયર",
        success_mantra: "સફળતા મંત્ર",
        thoughts_on_committee: "કમિટી પર વિચારો",
      },
      awardstudents: {
        filterPrompt:
          "કૃપા કરીને વિદ્યાર્થીઓ જોવા માટે ઓછામાં ઓછો એક ફિલ્ટર પસંદ કરો.",
        noStudentsFound: "કોઈ વિદ્યાર્થી મળ્યા નથી.",
        standard: "સ્ટાન્ડર્ડ",
        medium: "મધ્યમ",
        stream: "સ્ટ્રીમ",
        percentage: "ટકાવારી",
        year: "વર્ષ",
      },
      Business2: {
        details: "વ્યવસાયની વિગતો",
        phone: "ફોન નંબર",
        email: "ઈમેલ સરનામું",
        address: "સરનામું",
        location: "સ્થાન",
        category: "શ્રેણી",
        business_type: "વ્યવસાય પ્રકાર",
        name: "વ્યવસાયનું નામ",
        enterName: "વ્યવસાયનું નામ દાખલ કરો",
        city: "શહેર",
        enterCity: "શહેરનું નામ દાખલ કરો",
        state: "રાજ્ય",
        enterAddress: "સંપૂર્ણ વ્યવસાય સરનામું દાખલ કરો",
        contact: "સંપર્ક નંબર",
        enterContact: "10-અંકનો મોબાઇલ નંબર દાખલ કરો",
        enterEmail: "ઈમેલ સરનામું દાખલ કરો",
        type: "વ્યવસાય પ્રકાર",
        photo: "વ્યવસાયનો ફોટો",
        uploadPhoto: "વ્યવસાયનો ફોટો અપલોડ કરો",
        changePhoto: "વ્યવસાયનો ફોટો બદલો",
        logo: "વ્યવસાયનું લોગો",
        uploadLogo: "વ્યવસાયનું લોગો અપલોડ કરો",
        changeLogo: "વ્યવસાયનું લોગો બદલો",
        remove: "દૂર કરો",
        addBusiness: "વ્યવસાય ઉમેરો",
        editBusiness: "વ્યવસાય સંપાદિત કરો",
        addSuccess: "વ્યવસાય સફળતાપૂર્વક ઉમેરાયો",
        updateSuccess: "વ્યવસાય સફળતાપૂર્વક અપડેટ થયો",
        No_business_found: "કોઈ વ્યવસાય મળ્યા નથી",
        services_products: "સેવા/ઉત્પાદન",
      },
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: localStorage.getItem("appLanguage") || "en_US",
  fallbackLng: "en_US",
  interpolation: {
    escapeValue: false,
  },
});

export const changeLanguage = (lang: "en_US" | "gu_IN") => {
  i18n.changeLanguage(lang);
  localStorage.setItem("language", lang);
};

export default i18n;
